version: '3'
services:
  subgraph:
    image: postgres:15.0-alpine
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - '5432:5432'
    volumes:
      - ./src/providers/database/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
